/*
SQLyog Professional v12.09 (64 bit)
MySQL - 10.1.16-MariaDB : Database - dzob_poweramc
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`dzob_poweramc` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `dzob_poweramc`;

/*Table structure for table `action` */

DROP TABLE IF EXISTS `action`;

CREATE TABLE `action` (
  `CODE_ACTION` varchar(25) NOT NULL,
  `LIB_ACTION` varchar(100) NOT NULL,
  PRIMARY KEY (`CODE_ACTION`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `avoir` */

DROP TABLE IF EXISTS `avoir`;

CREATE TABLE `avoir` (
  `ID_PERSONNE` int(11) NOT NULL,
  `ID_AYANTDROIT` int(11) NOT NULL,
  `REFERENCE_PATRIMOINE` varchar(10) NOT NULL,
  PRIMARY KEY (`ID_PERSONNE`,`ID_AYANTDROIT`,`REFERENCE_PATRIMOINE`),
  KEY `FK_AVOIR3` (`REFERENCE_PATRIMOINE`),
  CONSTRAINT `FK_AVOIR` FOREIGN KEY (`REFERENCE_PATRIMOINE`) REFERENCES `immobilier` (`REFERENCE_PATRIMOINE`),
  CONSTRAINT `FK_AVOIR2` FOREIGN KEY (`ID_PERSONNE`, `ID_AYANTDROIT`) REFERENCES `ayant_droit` (`ID_PERSONNE`, `ID_AYANTDROIT`),
  CONSTRAINT `FK_AVOIR3` FOREIGN KEY (`REFERENCE_PATRIMOINE`) REFERENCES `mobilier` (`REFERENCE_PATRIMOINE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ayant_droit` */

DROP TABLE IF EXISTS `ayant_droit`;

CREATE TABLE `ayant_droit` (
  `ID_PERSONNE` int(11) NOT NULL,
  `ID_AYANTDROIT` int(11) NOT NULL AUTO_INCREMENT,
  `NOM` varchar(50) DEFAULT NULL,
  `PRENOM` varchar(100) DEFAULT NULL,
  `SEXE` varchar(1) DEFAULT NULL,
  `TELEPHONE` varchar(10) DEFAULT NULL,
  `ADRESSE` varchar(200) DEFAULT NULL,
  `DATE_NAISSANCE` date DEFAULT NULL,
  PRIMARY KEY (`ID_PERSONNE`,`ID_AYANTDROIT`),
  KEY `ID_AYANTDROIT` (`ID_AYANTDROIT`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Table structure for table `classeur` */

DROP TABLE IF EXISTS `classeur`;

CREATE TABLE `classeur` (
  `ID_CLASSEUR` int(11) NOT NULL AUTO_INCREMENT,
  `NOM_CLASSEUR` varchar(50) NOT NULL,
  `DATE_CLASSEUR` date NOT NULL,
  PRIMARY KEY (`ID_CLASSEUR`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Table structure for table `client` */

DROP TABLE IF EXISTS `client`;

CREATE TABLE `client` (
  `ID_PERSONNE` int(11) NOT NULL,
  `ID_CLIENT` int(11) NOT NULL AUTO_INCREMENT,
  `NOM` varchar(50) DEFAULT NULL,
  `PRENOM` varchar(100) DEFAULT NULL,
  `SEXE` varchar(1) DEFAULT NULL,
  `TELEPHONE` varchar(10) DEFAULT NULL,
  `ADRESSE` varchar(200) DEFAULT NULL,
  `DATE_NAISSANCE` date DEFAULT NULL,
  `TYPE_CLIENT` enum('PHYSIQUE','MORALE') NOT NULL,
  PRIMARY KEY (`ID_PERSONNE`,`ID_CLIENT`),
  KEY `ID_CLIENT` (`ID_CLIENT`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*Table structure for table `contenir` */

DROP TABLE IF EXISTS `contenir`;

CREATE TABLE `contenir` (
  `ID_DOC` int(11) NOT NULL,
  `ID_META` int(11) NOT NULL,
  PRIMARY KEY (`ID_DOC`,`ID_META`),
  KEY `FK_CONTENIR` (`ID_META`),
  CONSTRAINT `FK_CONTENIR` FOREIGN KEY (`ID_META`) REFERENCES `metadonnee` (`ID_META`),
  CONSTRAINT `FK_CONTENIR2` FOREIGN KEY (`ID_DOC`) REFERENCES `document` (`ID_DOC`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `courrier` */

DROP TABLE IF EXISTS `courrier`;

CREATE TABLE `courrier` (
  `REFERENCE` varchar(11) NOT NULL,
  `ACTEUR_COURRIER` varchar(250) NOT NULL,
  `ID_PERSONNE` int(11) NOT NULL,
  `ID_PRIORITE` int(11) NOT NULL,
  `ID_TYPECOURRIER` int(11) NOT NULL,
  `DATE` date NOT NULL,
  `OBJET_COURRIER` varchar(200) NOT NULL,
  `CONTENU_COURRIER` text,
  PRIMARY KEY (`REFERENCE`),
  KEY `FK_ASSOCIATION_9` (`ID_PRIORITE`),
  KEY `FK_ENVOYER3` (`ID_PERSONNE`),
  KEY `FK_ETRE_DE` (`ID_TYPECOURRIER`),
  CONSTRAINT `FK_ASSOCIATION_9` FOREIGN KEY (`ID_PRIORITE`) REFERENCES `priorite_courrier` (`ID_PRIORITE`),
  CONSTRAINT `FK_ENVOYER` FOREIGN KEY (`ID_PERSONNE`) REFERENCES `utilisateur` (`ID_PERSONNE`),
  CONSTRAINT `FK_ENVOYER2` FOREIGN KEY (`ID_PERSONNE`) REFERENCES `client` (`ID_PERSONNE`),
  CONSTRAINT `FK_ENVOYER3` FOREIGN KEY (`ID_PERSONNE`) REFERENCES `ayant_droit` (`ID_PERSONNE`),
  CONSTRAINT `FK_ETRE_DE` FOREIGN KEY (`ID_TYPECOURRIER`) REFERENCES `type_courrier` (`ID_TYPECOURRIER`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `document` */

DROP TABLE IF EXISTS `document`;

CREATE TABLE `document` (
  `ID_DOC` int(11) NOT NULL AUTO_INCREMENT,
  `ID_DOSSIER` int(11) NOT NULL,
  `TITRE_DOC` varchar(50) NOT NULL,
  `DESCRIPTION_DOC` varchar(5000) NOT NULL,
  `DATE_DOC` date NOT NULL,
  `DATE_EFFECTIVE` date DEFAULT NULL,
  `CREATEUR` varchar(50) NOT NULL,
  `SOURCE` varchar(150) NOT NULL,
  PRIMARY KEY (`ID_DOC`),
  KEY `ID_DOSSIER` (`ID_DOSSIER`),
  CONSTRAINT `document_ibfk_1` FOREIGN KEY (`ID_DOSSIER`) REFERENCES `dossier` (`ID_DOSSIER`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

/*Table structure for table `dossier` */

DROP TABLE IF EXISTS `dossier`;

CREATE TABLE `dossier` (
  `ID_DOSSIER` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CLASSEUR` int(11) NOT NULL,
  `ID_PERSONNE` int(11) DEFAULT NULL,
  `ID_CLIENT` int(11) NOT NULL,
  `DOS_ID_DOSSIER` int(11) DEFAULT NULL,
  `LIBELLE_DOSSIER` varchar(50) NOT NULL,
  `COMMENTAIRE_DOSSIER` varchar(500) NOT NULL,
  `DATE_CREATION` date NOT NULL,
  `DATE_DMDOSSIER` datetime DEFAULT NULL,
  `FRAIS_DOSSIER` float(10,4) NOT NULL,
  `ETAT_DOSSIER_TRAITEMENT` tinyint(1) NOT NULL,
  `STATUT_DOSSIER` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_DOSSIER`),
  KEY `FK_CLASSER` (`ID_CLASSEUR`),
  KEY `FK_DETENIR` (`ID_PERSONNE`,`ID_CLIENT`),
  KEY `FK_PARENTER_DOSSIER` (`DOS_ID_DOSSIER`),
  CONSTRAINT `FK_CLASSER` FOREIGN KEY (`ID_CLASSEUR`) REFERENCES `classeur` (`ID_CLASSEUR`),
  CONSTRAINT `FK_DETENIR` FOREIGN KEY (`ID_PERSONNE`, `ID_CLIENT`) REFERENCES `client` (`ID_PERSONNE`, `ID_CLIENT`),
  CONSTRAINT `FK_PARENTER_DOSSIER` FOREIGN KEY (`DOS_ID_DOSSIER`) REFERENCES `dossier` (`ID_DOSSIER`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;

/*Table structure for table `droits` */

DROP TABLE IF EXISTS `droits`;

CREATE TABLE `droits` (
  `ID_DROITS` int(11) NOT NULL AUTO_INCREMENT,
  `ETAT_DROIT` enum('ACTIF','INACTIF') NOT NULL,
  `LIBELLE_DROIT` varchar(250) NOT NULL,
  `COMMENTAIRE_DROIT` varchar(500) DEFAULT NULL,
  `DATE_DROIT` date NOT NULL,
  `DATE_DM` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_DROITS`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Table structure for table `evenement` */

DROP TABLE IF EXISTS `evenement`;

CREATE TABLE `evenement` (
  `ID_EVENEMENT` int(11) NOT NULL AUTO_INCREMENT,
  `REFERENCE_PATRIMOINE` varchar(10) NOT NULL,
  `LIBELLE_EVENEMENT` varchar(200) NOT NULL,
  `COMMENTAIRE_EVENEMENT` varchar(5000) DEFAULT NULL,
  `DATE_EVENEMENT` date NOT NULL,
  `ETAT_EVENEMENT` tinyint(1) NOT NULL,
  `DATE_REALISATION` date DEFAULT NULL,
  PRIMARY KEY (`ID_EVENEMENT`),
  KEY `FK_SURVENIR2` (`REFERENCE_PATRIMOINE`),
  CONSTRAINT `FK_SURVENIR` FOREIGN KEY (`REFERENCE_PATRIMOINE`) REFERENCES `immobilier` (`REFERENCE_PATRIMOINE`),
  CONSTRAINT `FK_SURVENIR2` FOREIGN KEY (`REFERENCE_PATRIMOINE`) REFERENCES `mobilier` (`REFERENCE_PATRIMOINE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `fichier` */

DROP TABLE IF EXISTS `fichier`;

CREATE TABLE `fichier` (
  `ID_FICHIER` int(11) NOT NULL AUTO_INCREMENT,
  `REFERENCE` varchar(11) NOT NULL,
  `NOM_FICHIER` varchar(30) NOT NULL,
  `FORMAT_FICHIER` varchar(10) DEFAULT NULL,
  `DATE_EFFECTIVE` date DEFAULT NULL,
  `CREATEUR` varchar(500) NOT NULL,
  `SOURCE` varchar(500) NOT NULL,
  PRIMARY KEY (`ID_FICHIER`),
  KEY `FK_JOINTURE` (`REFERENCE`),
  CONSTRAINT `FK_JOINTURE` FOREIGN KEY (`REFERENCE`) REFERENCES `courrier` (`REFERENCE`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=latin1;

/*Table structure for table `finance` */

DROP TABLE IF EXISTS `finance`;

CREATE TABLE `finance` (
  `ID_FINANCE` int(11) NOT NULL AUTO_INCREMENT,
  `REFERENCE_PATRIMOINE` varchar(10) NOT NULL,
  `MONTANT` float(10,2) NOT NULL,
  `DATE_FINANCE` date NOT NULL,
  `NATURE_FINANCE` varchar(30) NOT NULL,
  PRIMARY KEY (`ID_FINANCE`),
  KEY `FK_RAPPORTER2` (`REFERENCE_PATRIMOINE`),
  CONSTRAINT `FK_RAPPORTER` FOREIGN KEY (`REFERENCE_PATRIMOINE`) REFERENCES `immobilier` (`REFERENCE_PATRIMOINE`),
  CONSTRAINT `FK_RAPPORTER2` FOREIGN KEY (`REFERENCE_PATRIMOINE`) REFERENCES `mobilier` (`REFERENCE_PATRIMOINE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `fonction_profil` */

DROP TABLE IF EXISTS `fonction_profil`;

CREATE TABLE `fonction_profil` (
  `CODE_PROFIL` varchar(100) NOT NULL,
  `ID_FONCT` int(11) NOT NULL,
  PRIMARY KEY (`CODE_PROFIL`,`ID_FONCT`),
  KEY `FK_FONCTION_PROFIL` (`ID_FONCT`),
  CONSTRAINT `FK_FONCTION_PROFIL` FOREIGN KEY (`ID_FONCT`) REFERENCES `fonctionnalite` (`ID_FONCT`),
  CONSTRAINT `FK_FONCTION_PROFIL2` FOREIGN KEY (`CODE_PROFIL`) REFERENCES `profil` (`CODE_PROFIL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `fonction_user` */

DROP TABLE IF EXISTS `fonction_user`;

CREATE TABLE `fonction_user` (
  `IDPERSONNE` int(11) NOT NULL,
  `IDENTIFIANT` int(11) NOT NULL,
  `ID_FONCT` int(11) NOT NULL,
  PRIMARY KEY (`IDPERSONNE`,`IDENTIFIANT`,`ID_FONCT`),
  KEY `FK_FONCTION_USER` (`ID_FONCT`),
  CONSTRAINT `FK_FONCTION_USER` FOREIGN KEY (`ID_FONCT`) REFERENCES `fonctionnalite` (`ID_FONCT`),
  CONSTRAINT `FK_FONCTION_USER2` FOREIGN KEY (`IDPERSONNE`, `IDENTIFIANT`) REFERENCES `utilisateur` (`ID_PERSONNE`, `IDENTIFIANT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `fonctionnalite` */

DROP TABLE IF EXISTS `fonctionnalite`;

CREATE TABLE `fonctionnalite` (
  `ID_FONCT` int(11) NOT NULL AUTO_INCREMENT,
  `ID_MENU` int(11) NOT NULL,
  `NAME_FONCT` varchar(50) NOT NULL,
  `LIBEL_FONCT` varchar(120) NOT NULL,
  `FONCT_URL` varchar(50) NOT NULL,
  `CONTROLE_FONCT` varchar(5) NOT NULL,
  `NUM_ORDREFONCT` varchar(15) NOT NULL,
  `DESCRIPTION_FONCT` varchar(120) DEFAULT NULL,
  PRIMARY KEY (`ID_FONCT`),
  KEY `FK_ETRE_DANS` (`ID_MENU`),
  CONSTRAINT `FK_ETRE_DANS` FOREIGN KEY (`ID_MENU`) REFERENCES `menu` (`ID_MENU`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

/*Table structure for table `frais` */

DROP TABLE IF EXISTS `frais`;

CREATE TABLE `frais` (
  `ID_FRAIS` int(11) NOT NULL AUTO_INCREMENT,
  `ID_DOSSIER` int(11) NOT NULL,
  `MONTANT` float(10,2) NOT NULL,
  `DATE_REGLE` date DEFAULT NULL,
  PRIMARY KEY (`ID_FRAIS`),
  KEY `FK_NECESSITER` (`ID_DOSSIER`),
  CONSTRAINT `FK_NECESSITER` FOREIGN KEY (`ID_DOSSIER`) REFERENCES `dossier` (`ID_DOSSIER`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*Table structure for table `gr_usager` */

DROP TABLE IF EXISTS `gr_usager`;

CREATE TABLE `gr_usager` (
  `ID_DROITS` int(11) NOT NULL,
  `ID_PERSONNE` int(11) NOT NULL,
  `IDENTIFIANT` int(11) NOT NULL,
  `ID_DOSSIER` int(11) NOT NULL,
  `GR_LIBELLE` varchar(50) NOT NULL,
  `GR_DESCRIPTION` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`ID_DROITS`,`ID_PERSONNE`,`IDENTIFIANT`,`ID_DOSSIER`),
  KEY `FK_GR_USAGER` (`ID_DOSSIER`),
  KEY `FK_GR_USAGER3` (`ID_PERSONNE`,`IDENTIFIANT`),
  CONSTRAINT `FK_GR_USAGER` FOREIGN KEY (`ID_DOSSIER`) REFERENCES `dossier` (`ID_DOSSIER`),
  CONSTRAINT `FK_GR_USAGER2` FOREIGN KEY (`ID_DROITS`) REFERENCES `droits` (`ID_DROITS`),
  CONSTRAINT `FK_GR_USAGER3` FOREIGN KEY (`ID_PERSONNE`, `IDENTIFIANT`) REFERENCES `utilisateur` (`ID_PERSONNE`, `IDENTIFIANT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `immobilier` */

DROP TABLE IF EXISTS `immobilier`;

CREATE TABLE `immobilier` (
  `REFERENCE_PATRIMOINE` varchar(10) NOT NULL,
  `ID_IMMOBILIER` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PERSONNE` int(11) DEFAULT NULL,
  `ID_AYANTDROIT` int(11) DEFAULT NULL,
  `DESCRIPTION_IMMO` varchar(5000) NOT NULL,
  `ADRESSE` varchar(200) NOT NULL,
  `LATITUDE` decimal(10,4) DEFAULT NULL,
  `LONGITUDE` decimal(10,4) DEFAULT NULL,
  PRIMARY KEY (`REFERENCE_PATRIMOINE`,`ID_IMMOBILIER`),
  KEY `FK_ETRE_RESPONSABLE` (`ID_PERSONNE`,`ID_AYANTDROIT`),
  KEY `ID_IMMOBILIER` (`ID_IMMOBILIER`),
  CONSTRAINT `FK_ETRE_RESPONSABLE` FOREIGN KEY (`ID_PERSONNE`, `ID_AYANTDROIT`) REFERENCES `ayant_droit` (`ID_PERSONNE`, `ID_AYANTDROIT`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Table structure for table `livre_traitement` */

DROP TABLE IF EXISTS `livre_traitement`;

CREATE TABLE `livre_traitement` (
  `ID_LT` int(11) NOT NULL AUTO_INCREMENT,
  `NOM_TRAITEMENT` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_LT`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Table structure for table `menu` */

DROP TABLE IF EXISTS `menu`;

CREATE TABLE `menu` (
  `ID_MENU` int(11) NOT NULL AUTO_INCREMENT,
  `MEN_ID_MENU` int(11) DEFAULT NULL,
  `NAME_MENU` varchar(50) NOT NULL,
  `LIBEL_MENU` varchar(120) NOT NULL,
  `ICONE_NAME_MENU` varchar(50) DEFAULT 'fa-desktop',
  `CONTROLE` varchar(5) NOT NULL,
  `NUM_ORDREMENU` varchar(15) DEFAULT NULL,
  `MENU_URL` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_MENU`),
  KEY `FK_PARENTER_MENU` (`MEN_ID_MENU`),
  CONSTRAINT `FK_PARENTER_MENU` FOREIGN KEY (`MEN_ID_MENU`) REFERENCES `menu` (`ID_MENU`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

/*Table structure for table `metadonnee` */

DROP TABLE IF EXISTS `metadonnee`;

CREATE TABLE `metadonnee` (
  `ID_META` int(11) NOT NULL AUTO_INCREMENT,
  `ID_TYPEMETA` int(11) NOT NULL,
  `META_LIBELLE` varchar(50) NOT NULL,
  `META_CONTENU` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_META`),
  KEY `FK_DEFINIR` (`ID_TYPEMETA`),
  CONSTRAINT `FK_DEFINIR` FOREIGN KEY (`ID_TYPEMETA`) REFERENCES `type_metadonnee` (`ID_TYPEMETA`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Table structure for table `mobilier` */

DROP TABLE IF EXISTS `mobilier`;

CREATE TABLE `mobilier` (
  `REFERENCE_PATRIMOINE` varchar(10) NOT NULL,
  `ID_MOBILIER` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PERSONNE` int(11) NOT NULL,
  `ID_AYANTDROIT` int(11) NOT NULL,
  `DESCRIPTION_MO` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`REFERENCE_PATRIMOINE`,`ID_MOBILIER`),
  KEY `FK_ETRE_RESPONSABLE2` (`ID_PERSONNE`,`ID_AYANTDROIT`),
  KEY `ID_MOBILIER` (`ID_MOBILIER`),
  CONSTRAINT `FK_ETRE_RESPONSABLE2` FOREIGN KEY (`ID_PERSONNE`, `ID_AYANTDROIT`) REFERENCES `ayant_droit` (`ID_PERSONNE`, `ID_AYANTDROIT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `modele` */

DROP TABLE IF EXISTS `modele`;

CREATE TABLE `modele` (
  `ID_MODELE` int(11) NOT NULL AUTO_INCREMENT,
  `NOM_MODELE` varchar(100) NOT NULL,
  `SOURCE_MODELE` varchar(150) DEFAULT NULL,
  `CONTENU_MODELE` text NOT NULL,
  `NB_PARAMETRE` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID_MODELE`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Table structure for table `modifier` */

DROP TABLE IF EXISTS `modifier`;

CREATE TABLE `modifier` (
  `ID_VERSION` int(11) NOT NULL,
  `ID_DOSSIER` int(11) NOT NULL,
  PRIMARY KEY (`ID_VERSION`,`ID_DOSSIER`),
  KEY `FK_MODIFIER` (`ID_DOSSIER`),
  CONSTRAINT `FK_MODIFIER` FOREIGN KEY (`ID_DOSSIER`) REFERENCES `dossier` (`ID_DOSSIER`),
  CONSTRAINT `FK_MODIFIER2` FOREIGN KEY (`ID_VERSION`) REFERENCES `versionning` (`ID_VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `patrimoine` */

DROP TABLE IF EXISTS `patrimoine`;

CREATE TABLE `patrimoine` (
  `ID_PATRIMOINE` int(11) NOT NULL AUTO_INCREMENT,
  `REFERENCE_PATRIMOINE` varchar(50) NOT NULL,
  `NOM_PATRIMOINE` varchar(300) NOT NULL,
  PRIMARY KEY (`ID_PATRIMOINE`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Table structure for table `priorite_courrier` */

DROP TABLE IF EXISTS `priorite_courrier`;

CREATE TABLE `priorite_courrier` (
  `ID_PRIORITE` int(11) NOT NULL AUTO_INCREMENT,
  `NATURE_COURRIER` varchar(50) NOT NULL,
  `CLASSER` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_PRIORITE`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `profil` */

DROP TABLE IF EXISTS `profil`;

CREATE TABLE `profil` (
  `CODE_PROFIL` varchar(100) NOT NULL,
  `LIBELLE` varchar(200) NOT NULL,
  PRIMARY KEY (`CODE_PROFIL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `sys_log` */

DROP TABLE IF EXISTS `sys_log`;

CREATE TABLE `sys_log` (
  `ID_LOG` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_ACTION` varchar(25) NOT NULL,
  `ID_PERSONNE` int(11) DEFAULT NULL,
  `IDENTIFIANT` int(11) NOT NULL,
  `DATE_LOG` datetime NOT NULL,
  `TABLE_LOG` varchar(50) NOT NULL,
  `LIB_LOG` text NOT NULL,
  PRIMARY KEY (`ID_LOG`),
  KEY `FK_EFFECTUER` (`CODE_ACTION`),
  KEY `FK_FAIRE` (`ID_PERSONNE`,`IDENTIFIANT`),
  CONSTRAINT `FK_EFFECTUER` FOREIGN KEY (`CODE_ACTION`) REFERENCES `action` (`CODE_ACTION`),
  CONSTRAINT `FK_FAIRE` FOREIGN KEY (`ID_PERSONNE`, `IDENTIFIANT`) REFERENCES `utilisateur` (`ID_PERSONNE`, `IDENTIFIANT`)
) ENGINE=InnoDB AUTO_INCREMENT=117 DEFAULT CHARSET=latin1;

/*Table structure for table `sys_param` */

DROP TABLE IF EXISTS `sys_param`;

CREATE TABLE `sys_param` (
  `PARAM_CODE` varchar(50) NOT NULL,
  `PARAM_VALUE` varchar(600) NOT NULL,
  `PARAM_DESC` varchar(1500) NOT NULL,
  PRIMARY KEY (`PARAM_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `traitement` */

DROP TABLE IF EXISTS `traitement`;

CREATE TABLE `traitement` (
  `ID_DOSSIER` int(11) NOT NULL,
  `ID_LT` int(11) NOT NULL,
  `ID_TRAITEMENT` int(11) NOT NULL AUTO_INCREMENT,
  `ETAT_TRAITEMENT` tinyint(1) NOT NULL,
  `COMMENTAIRE_TRAITEMENT` text,
  `DATE_DEBUT` date NOT NULL,
  `DATE_FIN` date DEFAULT NULL,
  `DATE_PREVUE` date NOT NULL,
  PRIMARY KEY (`ID_DOSSIER`,`ID_LT`,`ID_TRAITEMENT`),
  KEY `ID_TRAITEMENT` (`ID_TRAITEMENT`),
  KEY `FK_TRAITEMENT_LIVRE` (`ID_LT`),
  CONSTRAINT `FK_TRAITEMENT_DOSSIER` FOREIGN KEY (`ID_DOSSIER`) REFERENCES `dossier` (`ID_DOSSIER`),
  CONSTRAINT `FK_TRAITEMENT_LIVRE` FOREIGN KEY (`ID_LT`) REFERENCES `livre_traitement` (`ID_LT`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Table structure for table `type_courrier` */

DROP TABLE IF EXISTS `type_courrier`;

CREATE TABLE `type_courrier` (
  `ID_TYPECOURRIER` int(11) NOT NULL AUTO_INCREMENT,
  `NOM_TYPE` varchar(25) NOT NULL,
  PRIMARY KEY (`ID_TYPECOURRIER`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Table structure for table `type_metadonnee` */

DROP TABLE IF EXISTS `type_metadonnee`;

CREATE TABLE `type_metadonnee` (
  `ID_TYPEMETA` int(11) NOT NULL AUTO_INCREMENT,
  `LIBELLE_TYPEMETA` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_TYPEMETA`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Table structure for table `user_profil` */

DROP TABLE IF EXISTS `user_profil`;

CREATE TABLE `user_profil` (
  `CODE_PROFIL` varchar(100) NOT NULL,
  `ID_PERSONNE` int(11) NOT NULL,
  `IDENTIFIANT` int(11) NOT NULL,
  PRIMARY KEY (`CODE_PROFIL`,`ID_PERSONNE`,`IDENTIFIANT`),
  KEY `FK_USER_PROFIL` (`ID_PERSONNE`,`IDENTIFIANT`),
  CONSTRAINT `FK_USER_PROFIL` FOREIGN KEY (`ID_PERSONNE`, `IDENTIFIANT`) REFERENCES `utilisateur` (`ID_PERSONNE`, `IDENTIFIANT`),
  CONSTRAINT `FK_USER_PROFIL2` FOREIGN KEY (`CODE_PROFIL`) REFERENCES `profil` (`CODE_PROFIL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `utilisateur` */

DROP TABLE IF EXISTS `utilisateur`;

CREATE TABLE `utilisateur` (
  `ID_PERSONNE` int(11) NOT NULL,
  `IDENTIFIANT` int(11) NOT NULL AUTO_INCREMENT,
  `NOM` varchar(50) DEFAULT NULL,
  `PRENOM` varchar(100) DEFAULT NULL,
  `SEXE` varchar(1) DEFAULT NULL,
  `TELEPHONE` varchar(10) DEFAULT NULL,
  `ADRESSE` varchar(200) DEFAULT NULL,
  `DATE_NAISSANCE` date DEFAULT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `USERNAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(500) NOT NULL,
  `AUTH_KEY` varchar(50) NOT NULL,
  `ACCESS_TOKEN` varchar(50) DEFAULT NULL,
  `ETAT` enum('ACTIF','INACTIF') NOT NULL,
  `DM_MODIFICATION` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_PERSONNE`,`IDENTIFIANT`),
  KEY `IDENTIFIANT` (`IDENTIFIANT`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

/*Table structure for table `valeur` */

DROP TABLE IF EXISTS `valeur`;

CREATE TABLE `valeur` (
  `ID_VALEUR` int(11) NOT NULL AUTO_INCREMENT,
  `REFERENCE_PATRIMOINE` varchar(10) NOT NULL,
  `MONTANT` float(10,2) NOT NULL,
  `DATE_DEBUT` date NOT NULL,
  `DATE_FIN` date DEFAULT NULL,
  PRIMARY KEY (`ID_VALEUR`),
  KEY `FK_VALOIR2` (`REFERENCE_PATRIMOINE`),
  CONSTRAINT `FK_VALOIR` FOREIGN KEY (`REFERENCE_PATRIMOINE`) REFERENCES `immobilier` (`REFERENCE_PATRIMOINE`),
  CONSTRAINT `FK_VALOIR2` FOREIGN KEY (`REFERENCE_PATRIMOINE`) REFERENCES `mobilier` (`REFERENCE_PATRIMOINE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `versionning` */

DROP TABLE IF EXISTS `versionning`;

CREATE TABLE `versionning` (
  `ID_VERSION` int(11) NOT NULL AUTO_INCREMENT,
  `DATE_DMVERSION` datetime NOT NULL,
  `DM_PAR` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
