/*------- 17/07/2017-------------------------------------------*/
/*--------MENU------------------*/
INSERT INTO MENU(MEN_ID_MENU,NAME_MENU,LIBEL_MENU,ICONE_NAME_MENU,CONTROLE,NUM_ORDREMENU,MENU_URL) VALUES (NULL,'MGestionProfil','Gestion de Profil','fichier.ico','NON',1,NULL);
INSERT INTO MENU(MEN_ID_MENU,NAME_MENU,LIBEL_MENU,ICONE_NAME_MENU,CONTROLE,NUM_ORDREMENU,MENU_URL) VALUES (NULL,'MAdministration','Administration','administration.ico','OUI',2,NULL);

/*--------FONCTIONNALITE------------------*/
/*--Fichier*/
INSERT INTO FONCTIONNALITE (ID_MENU,NAME_FONCT,LIBEL_FONCT,FONCT_URL,CONTROLE_FONCT,NUM_ORDREFONCT,DESCRIPTION_FONCT) VALUES(1,'SMChangerMDP','Changement de mot de passe','profile','OUI',1,'Page de modification des informations de l''utilisateur');

/*----Administration--------*/
INSERT INTO FONCTIONNALITE (ID_MENU,NAME_FONCT,LIBEL_FONCT,FONCT_URL,CONTROLE_FONCT,NUM_ORDREFONCT,DESCRIPTION_FONCT) VALUES(2,'SMGestionMenu','Gestion des Menus','menu','OUI',2,'Gestion du regroupement des fonctionnalités');
INSERT INTO FONCTIONNALITE (ID_MENU,NAME_FONCT,LIBEL_FONCT,FONCT_URL,CONTROLE_FONCT,NUM_ORDREFONCT,DESCRIPTION_FONCT) VALUES(2,'SMGestionProfil','Gestion des Profils','profilefonct','OUI',3,'Gestion des profils des utilisateurs');
INSERT INTO FONCTIONNALITE (ID_MENU,NAME_FONCT,LIBEL_FONCT,FONCT_URL,CONTROLE_FONCT,NUM_ORDREFONCT,DESCRIPTION_FONCT) VALUES(2,'SMGestionUtilisateur','Gestion des Utilisateurs','utilisateur','OUI',4,'Gestion des utilisateurs');
INSERT INTO FONCTIONNALITE (ID_MENU,NAME_FONCT,LIBEL_FONCT,FONCT_URL,CONTROLE_FONCT,NUM_ORDREFONCT,DESCRIPTION_FONCT) VALUES(2,'SMGestionDA','Gestion des Droits d''Accès','gestda','OUI',5,'Gestion des Droits d''Accès aux differentes fonctionnalités');
INSERT INTO FONCTIONNALITE (ID_MENU,NAME_FONCT,LIBEL_FONCT,FONCT_URL,CONTROLE_FONCT,NUM_ORDREFONCT,DESCRIPTION_FONCT) VALUES(2,'SMParamSysteme','Paramètre Système','systeme','OUI',6,'Paramètre Système');
INSERT INTO FONCTIONNALITE (ID_MENU,NAME_FONCT,LIBEL_FONCT,FONCT_URL,CONTROLE_FONCT,NUM_ORDREFONCT,DESCRIPTION_FONCT) VALUES(2,'SMJournalSysteme','Journal Système','syslog','OUI',7,'Journal de l''historique des systèmes');

/*-----ACTION-----*/
INSERT INTO ACTION(CODE_ACTION,LIB_ACTION) VALUES ('CREATE','Enregistrement');
INSERT INTO ACTION(CODE_ACTION,LIB_ACTION) VALUES ('UPDATE','Modification');
INSERT INTO ACTION(CODE_ACTION,LIB_ACTION) VALUES ('DELETE','Suppression');
INSERT INTO ACTION(CODE_ACTION,LIB_ACTION) VALUES ('PRINT','Impression');
INSERT INTO ACTION(CODE_ACTION,LIB_ACTION) VALUES ('SELECT','Consultation');
/*-----SYS_PARAM-----*/
INSERT INTO SYS_PARAM(PARAM_CODE,PARAM_VALUE,PARAM_DESC) VALUES ('TAUX_TVA','18','Taux de la TVA');
INSERT INTO SYS_PARAM(PARAM_CODE,PARAM_VALUE,PARAM_DESC) VALUES ('REPORT_DIR_NAME','Reports','Nom du repertoire des états');
INSERT INTO SYS_PARAM(PARAM_CODE,PARAM_VALUE,PARAM_DESC) VALUES ('APPLICATION_LABEL','DZOB','Label à afficher sur le menu principal');
INSERT INTO SYS_PARAM(PARAM_CODE,PARAM_VALUE,PARAM_DESC) VALUES ('APPLICATION_LOGO_NAME','logoApp.png','Le nom du fichier logo de l''application');
INSERT INTO SYS_PARAM(PARAM_CODE,PARAM_VALUE,PARAM_DESC) VALUES ('ICONE_DIR_NAME','icones','Nom du répertoire des icônes des menus');
